// Mock data — fictional setting "Vasteria"
const CAMPAIGNS = [
  {
    id: "c1",
    name: "A Coroa do Lago Cinza",
    setting: "Vasteria — Reino de Aldoria",
    system: "D&D 5e",
    sessions: 14,
    nextSession: "Sex, 10 mai • 20h",
    players: 5,
    level: "Nível 6",
    status: "ativa",
    dm: "Helena Ravari",
    progress: 0.62,
    accent: "#d8a25a",
    cover: "linear-gradient(135deg, #2a1a0e 0%, #5a2e10 50%, #d8a25a 130%)",
    summary: "Os heróis seguem rastros de um culto ancestral nas margens enevoadas do Lago Cinza. A coroa, perdida há séculos, reapareceu — mas a um custo terrível.",
    tags: ["alta-fantasia", "investigação", "horror leve"],
  },
  {
    id: "c2",
    name: "Marés de Korhen",
    setting: "Arquipélago de Korhen",
    system: "D&D 5e",
    sessions: 7,
    nextSession: "Dom, 12 mai • 19h",
    players: 4,
    level: "Nível 4",
    status: "ativa",
    dm: "Helena Ravari",
    progress: 0.31,
    accent: "#6da5c8",
    cover: "linear-gradient(135deg, #08182a 0%, #163554 50%, #6da5c8 130%)",
    summary: "Piratas, deuses do mar adormecidos e ilhas que desaparecem com a maré alta. Uma campanha de exploração naval na fronteira do mundo conhecido.",
    tags: ["pirataria", "exploração", "naval"],
  },
  {
    id: "c3",
    name: "O Coração da Cova",
    setting: "Subterrâneos de Vereth",
    system: "D&D 5e",
    sessions: 22,
    nextSession: "—",
    players: 6,
    level: "Nível 11",
    status: "pausada",
    dm: "Helena Ravari",
    progress: 0.85,
    accent: "#9d7bd8",
    cover: "linear-gradient(135deg, #1a0a2a 0%, #3a1a5a 50%, #9d7bd8 130%)",
    summary: "Profundezas onde o tempo se enrola. O grupo busca o coração de uma deusa esquecida no lugar onde a luz nunca alcança.",
    tags: ["underdark", "mistério", "épico"],
  },
];

const PLAYERS = [
  { id: "p1", name: "Marina Cruz", handle: "@marina", role: "jogadora", char: "Aelar Lirion", level: 6, hp: "42/42", status: "online", joined: "fev/2024", campaigns: 2, accent: "#d8a25a" },
  { id: "p2", name: "Tomás Reis", handle: "@tomas.reis", role: "jogador", char: "Brann Pedra-Forja", level: 6, hp: "58/58", status: "online", joined: "mar/2024", campaigns: 1, accent: "#c8643a" },
  { id: "p3", name: "Júlia Mendes", handle: "@ju", role: "jogadora", char: "Liriel Soprovento", level: 6, hp: "31/38", status: "ausente", joined: "fev/2024", campaigns: 3, accent: "#9d7bd8" },
  { id: "p4", name: "Pedro Vega", handle: "@pvega", role: "jogador", char: "Dranken", level: 6, hp: "50/52", status: "online", joined: "jan/2024", campaigns: 2, accent: "#7ba85d" },
  { id: "p5", name: "Ana Beatriz", handle: "@anabe", role: "jogadora", char: "Ysolde", level: 6, hp: "26/26", status: "offline", joined: "abr/2024", campaigns: 1, accent: "#6da5c8" },
  { id: "p6", name: "Rafael Kuroda", handle: "@rkuroda", role: "jogador", char: "Korr de Vinha", level: 4, hp: "33/33", status: "online", joined: "dez/2023", campaigns: 2, accent: "#c25555" },
  { id: "p7", name: "Larissa Ono", handle: "@lari", role: "jogadora", char: "Sylph", level: 4, hp: "22/24", status: "offline", joined: "ago/2024", campaigns: 1, accent: "#f0c170" },
];

const ACTIVITY = [
  { id: 1, who: "Marina", what: "subiu Aelar Lirion para o nível 6", when: "há 2h", icon: "spark", color: "#f0c170" },
  { id: 2, who: "Tomás", what: "rolou 19 em Atletismo (crítico próximo)", when: "há 5h", icon: "dice", color: "#d8a25a" },
  { id: 3, who: "Helena", what: "agendou sessão para sex 10 mai", when: "ontem", icon: "calendar", color: "#9d7bd8" },
  { id: 4, who: "Júlia", what: "adicionou anotação em 'Lago Cinza'", when: "ontem", icon: "feather", color: "#6da5c8" },
  { id: 5, who: "Pedro", what: "trocou poções no inventário", when: "2 dias", icon: "potion", color: "#7ba85d" },
];

// Character sheet data — Aelar Lirion
const CHARACTER = {
  name: "Aelar Lirion",
  player: "Marina Cruz",
  race: "Elfo da Madeira",
  class: "Patrulheiro",
  subclass: "Caçador",
  background: "Forasteiro",
  alignment: "Caótico Bom",
  level: 6,
  xp: 14200,
  xpNext: 23000,
  hp: 42,
  hpMax: 42,
  hpTemp: 0,
  ac: 16,
  speed: 35,
  init: 4,
  prof: 3,
  inspiration: true,
  hitDice: "6d10",
  deathSaves: { s: 0, f: 0 },
  abilities: [
    { name: "FOR", full: "Força", score: 12, mod: 1, save: 1, saveProf: false },
    { name: "DES", full: "Destreza", score: 18, mod: 4, save: 7, saveProf: true },
    { name: "CON", full: "Constituição", score: 14, mod: 2, save: 2, saveProf: false },
    { name: "INT", full: "Inteligência", score: 11, mod: 0, save: 0, saveProf: false },
    { name: "SAB", full: "Sabedoria", score: 16, mod: 3, save: 6, saveProf: true },
    { name: "CAR", full: "Carisma", score: 10, mod: 0, save: 0, saveProf: false },
  ],
  skills: [
    { name: "Acrobacia", abil: "DES", mod: 4, prof: false },
    { name: "Adestrar Animais", abil: "SAB", mod: 6, prof: true },
    { name: "Arcanismo", abil: "INT", mod: 0, prof: false },
    { name: "Atletismo", abil: "FOR", mod: 1, prof: false },
    { name: "Atuação", abil: "CAR", mod: 0, prof: false },
    { name: "Enganação", abil: "CAR", mod: 0, prof: false },
    { name: "Furtividade", abil: "DES", mod: 7, prof: true },
    { name: "História", abil: "INT", mod: 0, prof: false },
    { name: "Intimidação", abil: "CAR", mod: 0, prof: false },
    { name: "Intuição", abil: "SAB", mod: 6, prof: true },
    { name: "Investigação", abil: "INT", mod: 3, prof: true },
    { name: "Medicina", abil: "SAB", mod: 3, prof: false },
    { name: "Natureza", abil: "INT", mod: 3, prof: true },
    { name: "Percepção", abil: "SAB", mod: 6, prof: true },
    { name: "Persuasão", abil: "CAR", mod: 0, prof: false },
    { name: "Prestidigitação", abil: "DES", mod: 4, prof: false },
    { name: "Religião", abil: "INT", mod: 0, prof: false },
    { name: "Sobrevivência", abil: "SAB", mod: 6, prof: true },
  ],
  attacks: [
    { name: "Arco Longo +1", bonus: 8, dmg: "1d8+5", type: "perfurante", range: "150/600 pés" },
    { name: "Espada Curta", bonus: 7, dmg: "1d6+4", type: "perfurante", range: "corpo a corpo" },
    { name: "Adaga (arr.)", bonus: 7, dmg: "1d4+4", type: "perfurante", range: "20/60 pés" },
  ],
  spellSlots: [
    { level: 1, total: 4, used: 1 },
    { level: 2, total: 2, used: 0 },
  ],
  spells: [
    { lvl: 1, name: "Marca do Caçador", school: "Divinação", prep: true },
    { lvl: 1, name: "Cura de Ferimentos", school: "Evocação", prep: true },
    { lvl: 1, name: "Camuflar-se na Natureza", school: "Transmutação", prep: true },
    { lvl: 2, name: "Passos de Vento", school: "Transmutação", prep: true },
    { lvl: 2, name: "Localizar Objeto", school: "Adivinhação", prep: false },
  ],
  features: [
    { name: "Inimigo Predileto", desc: "Ferozes (gnolls). +2 nas jogadas de dano." },
    { name: "Explorador Natural", desc: "Florestas. Não se perde, terreno difícil normal." },
    { name: "Estilo de Luta", desc: "Arco e Flecha — +2 em ataques à distância." },
    { name: "Conjuração", desc: "Patrulheiro conjura magias usando Sabedoria." },
    { name: "Presa do Caçador", desc: "Bônus de dano contra alvo marcado." },
  ],
  inventory: [
    { name: "Arco Longo +1", qty: 1, weight: 2 },
    { name: "Aljava (32 flechas)", qty: 1, weight: 1 },
    { name: "Espada Curta", qty: 1, weight: 2 },
    { name: "Adaga", qty: 2, weight: 2 },
    { name: "Poção de Cura", qty: 3, weight: 1.5 },
    { name: "Capa Élfica", qty: 1, weight: 1 },
    { name: "Kit de Explorador", qty: 1, weight: 8 },
    { name: "Pó de Estrela (3 doses)", qty: 1, weight: 0.1 },
  ],
  money: { pc: 12, pp: 8, po: 142, pe: 4, pl: 1 },
  notes: "Aelar busca o pai desaparecido nas Florestas Nevadas. Carrega um medalhão de prata gravado com runas que brilha perto de criaturas mágicas. Devedor de favor a uma druida de Threwid.",
};

const QUICK_DICE = ["d4", "d6", "d8", "d10", "d12", "d20", "d100"];

const COMPENDIUM = [
  { id: "seed-magia-1", type: "Magia", name: "Bola de Fogo", lvl: "3º nível", school: "Evocação", desc: "Uma esfera incandescente irrompe em um ponto à sua escolha. 8d6 de fogo (TR Des).", color: "#c8643a", icon: "flame",
    classes: ["Mago", "Feiticeiro"], castTime: "1 ação", range: "45 m", components: { v: true, s: true, m: true, mDesc: "uma bolinha de guano de morcego e enxofre" }, duration: "Instantânea", damage: "8d6", damageType: "fogo", save: "Destreza" },
  { id: "seed-magia-2", type: "Magia", name: "Cura de Ferimentos", lvl: "1º nível", school: "Evocação", desc: "Uma criatura tocada recupera 1d8 + mod de conjuração de PV.", color: "#7ba85d", icon: "heart",
    classes: ["Clérigo", "Druida", "Paladino", "Ranger", "Bardo"], castTime: "1 ação", range: "Toque", components: { v: true, s: true, m: false }, duration: "Instantânea", damage: "1d8", damageType: "cura", save: "—" },
  { id: "seed-magia-3", type: "Magia", name: "Mãos Mágicas", lvl: "Truque", school: "Conjuração", desc: "Mão espectral que manipula objetos leves a até 9m de distância.", color: "#9d7bd8", icon: "spark",
    classes: ["Mago", "Feiticeiro", "Bruxo", "Bardo"], castTime: "1 ação", range: "9 m", components: { v: true, s: true, m: false }, duration: "1 minuto", damage: "—", damageType: "—", save: "—" },
  { id: "seed-classe-1", type: "Classe", name: "Mago", lvl: "Classe", school: "Dado de vida d6", desc: "Estudioso da magia arcana. Domina grimórios, rituais e a manipulação fundamental da realidade através do estudo formal.", color: "#6da5c8", icon: "book",
    hitDie: "d6", primaryAttr: "Inteligência", savingThrows: ["Inteligência", "Sabedoria"], skillCount: 2, skills: ["Arcanismo", "História", "Investigação", "Intuição", "Medicina", "Religião"],
    equipment: "Cajado ou adaga · Bolsa de componentes ou foco arcano · Mochila de erudito · Grimório",
    features: [
      { level: 1, name: "Conjuração", desc: "Conhece truques e magias do grimório. Usa Inteligência como atributo de conjuração." },
      { level: 1, name: "Recuperação Arcana", desc: "Recupera espaços de magia durante descanso curto, uma vez por dia." },
      { level: 2, name: "Tradição Arcana", desc: "Escolhe uma escola: Evocação, Abjuração, Ilusão, Adivinhação, Encantamento, Necromancia, Conjuração ou Transmutação." },
      { level: 18, name: "Domínio de Magia", desc: "Escolhe duas magias de 1º ou 2º nível para conjurar à vontade." },
    ] },
  { id: "seed-classe-2", type: "Classe", name: "Guerreiro", lvl: "Classe", school: "Dado de vida d10", desc: "Combatente disciplinado, mestre em armas e armaduras. Versátil no campo de batalha.", color: "#c25555", icon: "sword",
    hitDie: "d10", primaryAttr: "Força ou Destreza", savingThrows: ["Força", "Constituição"], skillCount: 2, skills: ["Acrobacia", "Adestrar Animais", "Atletismo", "História", "Intimidação", "Percepção", "Sobrevivência"],
    equipment: "Cota de malha ou couro batido · Arma marcial e escudo · Duas machadinhas · Mochila de aventureiro",
    features: [
      { level: 1, name: "Estilo de Luta", desc: "Escolhe uma especialização: Arquearia, Defesa, Duelo, Combate em Duas Armas, Proteção ou Armas Grandes." },
      { level: 1, name: "Retomar o Fôlego", desc: "Bônus + 1d10 de PV uma vez por descanso curto." },
      { level: 2, name: "Surto de Ação", desc: "Uma ação adicional no turno, uma vez por descanso." },
      { level: 3, name: "Arquétipo Marcial", desc: "Campeão, Mestre de Batalha ou Cavaleiro Místico." },
    ] },
  { id: "seed-hab-1", type: "Habilidade", name: "Ataque Extra", lvl: "Nível 5", school: "Guerreiro", desc: "Ao realizar a ação de Ataque no seu turno, pode atacar duas vezes em vez de uma.", color: "#d8a25a", icon: "sword",
    className: "Guerreiro", levelReq: 5, kind: "Passiva", cost: "—", effect: "Concede 2 ataques por ação. No nível 11, sobe para 3; no nível 20, para 4." },
  { id: "seed-hab-2", type: "Habilidade", name: "Fúria", lvl: "Nível 1", school: "Bárbaro", desc: "Entra em uma fúria selvagem, ganhando bônus de dano e resistência a dano físico.", color: "#c25555", icon: "flame",
    className: "Bárbaro", levelReq: 1, kind: "Ativa", cost: "Ação bônus · 2 usos/descanso longo", effect: "+2 dano corpo a corpo (Força). Resistência a dano cortante, perfurante e impacto. Vantagem em testes de Força. Dura 1 minuto." },
  { id: "seed-hab-3", type: "Habilidade", name: "Disparo Defensivo", lvl: "Nível 3", school: "Ranger", desc: "Quando atacado em corpo a corpo, dispara uma flecha como reação.", color: "#7ba85d", icon: "spark",
    className: "Ranger", levelReq: 3, kind: "Reação", cost: "1 reação", effect: "Ao ser alvo de um ataque corpo a corpo dentro do alcance da arma à distância, faz um ataque imediato contra o atacante." },
  { id: "seed-monstro-1", type: "Monstro", name: "Beholder", lvl: "ND 13", school: "Aberração Lendária", desc: "Olho central anula magia. 10 raios oculares de feitiços diversos.", color: "#c25555", icon: "eye" },
  { id: "seed-monstro-2", type: "Monstro", name: "Goblin", lvl: "ND 1/4", school: "Humanoide pequeno", desc: "Astuto, covarde em grupos pequenos, mortal em bandos.", color: "#7ba85d", icon: "skull" },
  { id: "seed-item-1", type: "Item", name: "Espada Vorpalina", lvl: "Lendário", school: "Arma — Espada Longa", desc: "Em um 20 natural contra alvo de tamanho Médio ou menor, decepa cabeça.", color: "#d8a25a", icon: "sword" },
  { id: "seed-item-2", type: "Item", name: "Manto Élfico", lvl: "Incomum", school: "Vestimenta", desc: "Vantagem em testes de Furtividade, desvantagem para vê-lo.", color: "#6da5c8", icon: "feather" },
  { id: "seed-regra-1", type: "Regra", name: "Vantagem & Desvantagem", lvl: "Regra Básica", school: "Mecânica", desc: "Role 2d20 e use o maior (vantagem) ou menor (desvantagem). Não se acumulam.", color: "#f0c170", icon: "dice" },
];

window.MOCK = { CAMPAIGNS, PLAYERS, ACTIVITY, CHARACTER, QUICK_DICE, COMPENDIUM };
